src/Entity/Reservation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReservationRepository")
 */
class Reservation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Freelancer", inversedBy="reserver")
     * @ORM\JoinColumn(nullable=false)
     */
    private $freelancer;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Tache", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_tache;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFreelancer(): ?Freelancer
    {
        return $this->freelancer;
    }

    public function setFreelancer(?Freelancer $freelancer): self
    {
        $this->freelancer = $freelancer;

        return $this;
    }

    public function getIdTache(): ?Tache
    {
        return $this->id_tache;
    }

    public function setIdTache(Tache $id_tache): self
    {
        $this->id_tache = $id_tache;

        return $this;
    }

   
}

templates/reservations/reservations.html.twig
{% extends 'base3.html.twig'%}
{% block body %}
<div>
<table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Type</th>
            <th scope="col">Description</th>
            <th scope="col">Technologie</th>
            <th scope="col">Côut</th>

            <th></th>
        </tr>
        </thead>
        <tbody>

                  {% for reserv in ti %}
                 
            <tr> 
                <th>{{reserv.id}}</th>
                
                <th>{{reserv.idTache.type}}</th>
                <th>{{reserv.idTache.description}}</th>
                <th>{{reserv.idTache.technologie}}</th>
                <th>{{reserv.idTache.cout}}</th>
                <th>
                    <a href="{{path('details',{'id':reserv.idTache.id})}}">
                        <button type="button" class="btn btn-primary">plus de détails</button>
                    </a>
                </th>
            </tr>
        {% endfor %}
          
        </tbody>
    </table>
    </div>

{% endblock %}